### ISSUE TITLE
remove ACS June 24 at concert hall from calendar + printable - show cancelled

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#32]
thanks for the sign-up switch

**Comment by andrewfn** [comment]
I've removed it from the calendars.
- Note that it automatically gets removed from the public version of the calendar within an hour or so of you unpublishing it.
- However you will still see it if you a logged in, since that shows unpublished concerts
- For the printed calendar I had to run a script and flush it out from our main cache.
