### ISSUE TITLE
change link on photos page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#36]
I had to create a different Flickr group pool.  "2017 TD Toronto Jazz Festival" 
I think it's working now.  I think if you just replace the ID with this (83625548@N05) instead of the similar ID for the previous pool it should bring up some new photos

**Comment by andrewfn** [comment]
I made the change but it gave me a blank screen so I put it back to how it was.
It looks like there are too many digits in your id.
Old:   3842718@N22
New:  83625548@N05

**Comment by andrewfn** [comment]
3485073@N23 works

**Comment by andrewfn** [comment]
I got to the bottom of the problem with the photo page on a tablet.
- It turns out that if it doesn't support flash, then a picture and caption are shown (which were not changed from last year). 
- I have updated the picture (which we can change if you want a different one) and put the correct caption in there.

### Unpublished ads showing
- I've not been able to reproduce this problem. Let me know if it's still happening.
