### ISSUE TITLE
please remove bottom 2 rows

### ISSUE THREAD

**Issue by brianblain** [jazzto/2017#38]
...and on monday we want to display the photo gallery on home page with the message "Thank You Jazz Fans"

use the pic below as the placeholder for mobile
![kc_roberts1](https://user-images.githubusercontent.com/11864078/27764587-da900696-5e6a-11e7-92f0-938b978b682b.JPG)

**Comment by andrewfn** [comment]
Bottom row gone now.
I'll switch to the photo gallery on Monday.

**Comment by andrewfn** [comment]
I've done what looks good to me. If you don't like it, just let me know and I'll change it.
### Mobile site:
- Use your picture from above which they click on to see the photo stream

### Desktop site:
- Use your picture **as well as and above** the photo stream since there is more space, plus it might look a little odd with just the photo stream
- This is what we did last year, and it worked.

**Comment by brianblain** [comment]
anna sent me slightly revised text but stand by to see if there's other changes  You did an amazing job again this year.  I can't imagine a faster response time from any web developer - big or small.

**Comment by andrewfn** [comment]
Thanks Brian. That's really great to hear! It's a very worthwhile organization so I want to make sure you get the best possible outcome. You have done a great job too, and make my life easy by being very specific in what you want.
The stats this year were virtually identical to last year (within around 0.5% overall difference for the last week)
Here's an analytics snapshot of the last 8 days during which we got around 1/4 million page views:
![image](https://user-images.githubusercontent.com/643683/27798861-e0eafb3c-5fe0-11e7-9f5a-3c1870239ea0.png)

**Comment by brianblain** [comment]
can you change the text to "Thank you to all the fans who came out to support us this year"
Smaller font

**Comment by andrewfn** [comment]
Done
